### ISSUE TITLE
Set up company root email accounts for aws registration

### ISSUE THREAD

**Issue by shawngerrard** [asterion-digital/asterion-as-code#12]
We should begin the process of creating shared group credentials and services. 

Currently, I can see the need for three primary group email accounts that will be mapped to specific permission/role levels in aws iams:

1. _root_ email account that can manage everything across all aws organizations/accounts. e.g - **root@asterion.digital**.
2. _administrator_ email account that can manage everything across all aws accounts/services within specific aws organizations. e.g - **administrator@asterion.digital**.
3. _customer_ email account that can manage automated communication to external parties. e.g - **hello@asterion.digital**.

Many services depend on email as a primary means of identification and communication. We have a company email service with g-suite that we could utilize for this purpose.

**Comment by jmhbnz** [comment]
This issue was discussed and prioritized on 20th April. It was agreed we would focus on item 1 as that is the key item we need to proceed with the aws account registration.

> "root email account that can manage everything across all aws organizations/accounts. e.g - [root@asterion.digital](mailto:root@asterion.digital).

Permissions were granted to @shawngerrard in  [admin.google.com](https://admin.google.com) so that we can proceed with registration of the root email account.

The new root user can be created here: https://admin.google.com/ac/users 

![image](https://user-images.githubusercontent.com/39425256/164287811-de039848-1e60-4726-b69d-4c0742036301.png)

**Comment by jmhbnz** [comment]
@shawngerrard has this been completed now that we have `org-asterion` in place?

**Comment by shawngerrard** [comment]
@jmhbnz Came here to leave an update and saw yours! :D

Yes, this one is done.
