### ISSUE TITLE
Define an aws organization in pulumi

### ISSUE THREAD

**Issue by shawngerrard** [asterion-digital/asterion-as-code#15]
We need to be able to define the asterion organization in pulumi when deploying our infrastructure in aws.

This organization must have access to all features, be easily identifiable, and will eventually define default member accounts and adopt tag policies to control the permissions across all aws services for this organization.

Refer to [aws organizations in pulumi](https://github.com/asterion-digital/asterion-as-code/blob/master/infra-aws/__main__.py) for notes on the pulumi-python implementation.

**Comment by jmhbnz** [comment]
This issue was discussed and prioritized on 20th April. We agreed that we will manage our organisation setup in aws via pulumi and using this repository.

We will add a third stack pattern to this repository using subdirectories of `org - <name>` in addition to our existing patterns of defining `infra - <name>` and `app - <name>` stacks.

This will give us flexibility to manage `org - asterion` as code while also being repeatable in future if additional orgs need to be created in aws.

**Comment by jmhbnz** [comment]
Hey @shawngerrard - with #18 now merged are we ok to close this issue and move to done on the board?
